<?php

namespace app\modules\interface_app\controllers;

use app\models\logger\DebugLogger;
use Yii;
use yii\web\Controller;
use app\models\bitrix\app\Client;

class MainController extends Controller
{
    public function runAction($id, $params = [])
    {
        $token = Yii::$app->params['modules']['interface_app']['token'] ?? null;
        $requestToken = Yii::$app->request->get('token');

        if(empty($requestToken) && $token !== $requestToken)
        {
            return $this->actionAccessDenied();
        }

        return parent::runAction($id, $params); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;

        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionInstall()
    {
        $auth = collect(Yii::$app->request->post());

        $logger = DebugLogger::instance("install");
        $logger->save($auth, $auth, "Данные приложения");

        if(Yii::$app->request->isPost)
        {
            if($auth->has("auth"))
            {
                $auth = $auth["auth"];
            }

            $app = new Client($auth);
            $app->updateConfig();
        }

        return $this->render("install");
    }

    public function actionAccessDenied()
    {
        return $this->render('access_denied');
    }
}
